#Morning light
- alias: Morning light on
  trigger:
    platform: time
    at: '07:20:00'
  condition:
    condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
#    - condition: state
#      entity_id: device_tracker.scott
#      state: 'home'
#    - platform: sun
#      event: sunset
#      offset: '-01:00:00'
    - condition: state
      entity_id: input_boolean.morning_light
      state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: light.bijkeuken

- alias: Morning light off
  trigger:
    platform: time
    at: '07:45:00'
  condition:
    condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
#    - condition: state
#      entity_id: device_tracker.scott
#      state: 'home'
#    - platform: numeric_state
#      entity_id: sun.sun
#      value_template: "{{ state.attributes.elevation }}"
#      # Can be a positive or negative number
#      above: 10.0
    - condition: state
      entity_id: input_boolean.morning_light
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: light.bijkeuken

#Vacation light living room and hallway
- alias: Vacation light on
  trigger:
    platform: time
    at: '18:20:00'
  condition:
    condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
    - condition: state
      entity_id: input_boolean.vacation_light
      state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: light.woonkamer, light.gang

- alias: Vacation light off
  trigger:
    platform: time
    at: '22:45:00'
  condition:
    condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
    - condition: state
      entity_id: input_boolean.vacation_light
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: light.woonkamer, light.gang

#Vacation light bedroom
- alias: Vacation light 2 on
  trigger:
    platform: time
    at: '22:20:00'
  condition:
    condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
    - condition: state
      entity_id: input_boolean.vacation_light
      state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: light.slaapkamer

- alias: Vacation light 2 off
  trigger:
    platform: time
    at: '23:45:00'
  condition:
    condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
    - condition: state
      entity_id: input_boolean.vacation_light
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: light.slaapkamer
